### PR TITLE
fix for uBO 1.25.0

### PR DESCRIPTION
**Pull request by stonecrusher**
I fixed my personal CSS for uBO 1.25.0 and think it will also suit everyone else. Only thing is that I didn't use color variables everywhere, but also "absolute" colors. So you may have a look at it, but it works for default.

### CODE REVIEW

**Comment by ghost** [comment]
It seems like you only used absolute colours where it was more necessary (as in, there were no appropriate variables in the colour scheme, because it was trying to show a rainbow or something)? That seems fine to me.

Thanks for taking care of this.

**Comment by stonecrusher** [comment]
@overdodactyl Please consider having a look at this repo / PRs after that year of stasis.

**Comment by ghost** [comment]
By the way, latest uBlock has changed the UI again, and it's gotten worse for us I'm afraid:

image

Not sure if the above patch would still resolve this?

I've read that there is a plan to include a dark interface within the addon itself, but until then.... It would be good to see you @overdodactyl :)

**Comment by stonecrusher** [comment]
> Not sure if the above patch would still resolve this?

No it doesn't.  
They had quite a big makeover concerning the structure, selectors and so on.
But I am positive it won't take too long for a native dark style as everything is already set up for dark style and you more or less just need to fill in the dark colors for the ~30 variables.

**Comment by hyiltiz** [comment]
My uBo still looks like the one shown above: https://docs.google.com/spreadsheets/d/1ZZ8JeDjz7C5cRVl8ovYYm2L3E0mjjebCxN7WUK1Nw2A. I just updated shadowfox as instructed (to the 2019 Jun 1 version). Is everything also seeing this and we are all awaiting a fix?

**Comment by stonecrusher** [comment]
It's not perfect / completely finished yet, but by now you can activate the built-in dark mode of uBO.

In the advanced settings, set `uiTheme` to `dark`.
https://github.com/gorhill/uBlock/wiki/Advanced-settings#uitheme

**Pull request closed without merging**
